let data = [
  {
    id: 0,
    pic: '/images/hyunbeom/wecode.jpeg',
    title: 'wecode_bootcamp',
    content: 'WeCode | 위코드',
    isLocationStory: false,
    isLocationFeeds: false,
    feedPic: '',
    firstLikeUser: '',
    likeCount: '',
    feedContent: '',
    feedFirstUser: '',
    feedFirstChat: '',
  },

  {
    id: 1,
    pic: '/images/hyunbeom/user1.jpeg',
    title: 'Brad_Pitt',
    content: 'I am happy',
    isLocationStory: true,
    isLocationFeeds: true,
    feedPic: '/images/hyunbeom/user1-feed.jpeg',
    firstLikeUser: 'Angelina_Jolie',
    likeCount: 47,
    feedContent: 'Please come and watch the movie...',
    feedFirstUser: 'Chris_Pratt',
    feedFirstChat: 'OMG I luv it',
  },

  {
    id: 2,
    pic: '/images/hyunbeom/user2.jpeg',
    title: 'Angelina_Jolie',
    content: 'I am glad to hear that',
    isLocationStory: true,
    isLocationFeeds: false,
    feedPic: '',
    firstLikeUser: '',
    likeCount: '',
    feedContent: '',
    feedFirstUser: '',
    feedFirstChat: '',
  },
  {
    id: 3,
    pic: '/images/hyunbeom/user3.jpeg',
    title: 'Don_Lee',
    content: '진실의 방으로',
    isLocationStory: true,
    isLocationFeeds: false,
    feedPic: '',
    firstLikeUser: '',
    likeCount: '',
    feedContent: '',
    feedFirstUser: '',
    feedFirstChat: '',
  },
  {
    id: 4,
    pic: '/images/hyunbeom/user4.jpeg',
    title: 'Mr_Goo',
    content: '추앙해요',
    isLocationStory: true,
    isLocationFeeds: false,
    feedPic: '',
    firstLikeUser: '',
    likeCount: '',
    feedContent: '',
    feedFirstUser: '',
    feedFirstChat: '',
  },
  {
    id: 5,
    pic: '/images/hyunbeom/user5.jpeg',
    title: 'Tom_Holland',
    content: '회원님을 위한 추천',
    isLocationStory: false,
    isLocationFeeds: false,
    feedPic: '',
    firstLikeUser: '',
    likeCount: '',
    feedContent: '',
    feedFirstUser: '',
    feedFirstChat: '',
  },

  {
    id: 6,
    pic: '/images/hyunbeom/user6.jpeg',
    title: 'Chris_Hemsworth',
    content: 'Instagram 신규 가입',
    isLocationStory: false,
    isLocationFeeds: false,
    feedPic: '',
    firstLikeUser: '',
    likeCount: '',
    feedContent: '',
    feedFirstUser: '',
    feedFirstChat: '',
  },
  {
    id: 7,
    pic: '/images/hyunbeom/user7.jpeg',
    title: 'Chris_Pratt',
    content: 'Instagram 신규 가입',
    isLocationStory: false,
    isLocationFeeds: false,
    feedPic: '',
    firstLikeUser: '',
    likeCount: '',
    feedContent: '',
    feedFirstUser: '',
    feedFirstChat: '',
  },
  {
    id: 8,
    pic: '/images/hyunbeom/wecode3.jpeg',
    title: 'wecode_korea',
    content: '',
    isLocationStory: false,
    isLocationFeeds: false,
    feedPic: '',
    firstLikeUser: '',
    likeCount: '',
    feedContent: '',
    feedFirstUser: '',
    feedFirstChat: '',
  },
  {
    id: 9,
    pic: '/images/hyunbeom/myPhoto.jpeg',
    title: 'wecode_hyunbeom',
    content: 'hi there',
    isLocationStory: false,
    isLocationFeeds: false,
    feedPic: '',
    firstLikeUser: '',
    likeCount: '',
    feedContent: '',
    feedFirstUser: '',
    feedFirstChat: '',
  },
  {
    id: 10,
    pic: '/images/hyunbeom/wecode2.jpeg',
    title: 'Wecode',
    content: '강남구 테헤란로 427 서울',
    isLocationStory: false,
    isLocationFeeds: false,
    feedPic: '',
    firstLikeUser: '',
    likeCount: '',
    feedContent: '',
    feedFirstUser: '',
    feedFirstChat: '',
  },
  {
    id: 11,
    pic: '/images/hyunbeom/myPhoto.jpeg',
    title: 'hyunbeom_hi',
    content: '',
    isLocationStory: false,
    isLocationFeeds: true,
    feedPic: '/images/hyunbeom/feed.jpeg',
    firstLikeUser: 'Mr_Goo',
    likeCount: 10,
    feedContent: '위워크에서 진행한 도자기 클래스...',
    feedFirstUser: 'Don_Lee',
    feedFirstChat: '귀엽게 잘 만들었네',
  },
  {
    id: 12,
    pic: '/images/hyunbeom/user8.jpeg',
    title: 'Tom_Holland',
    content: '',
    isLocationStory: false,
    isLocationFeeds: true,
    feedPic: '/images/hyunbeom/user8-feed.jpeg',
    firstLikeUser: 'Chris_Hemsworth',
    likeCount: 70,
    feedContent: 'Tom Holland, Tobey Maguire, and Andrew Garfield... ',
    feedFirstUser: 'Andrew_Garfield',
    feedFirstChat: 'So exciting',
  },
  {
    id: 13,
    pic: '/images/hyunbeom/user9.jpeg',
    title: 'Robert_Downey_Jr',
    content: '',
    isLocationStory: false,
    isLocationFeeds: true,
    feedPic: '/images/hyunbeom/user9-feed.jpeg',
    firstLikeUser: 'Captin_America',
    likeCount: 3000,
    feedContent: 'I Am Iron Man...',
    feedFirstUser: 'Tom_Holland',
    feedFirstChat: 'Thank you for all your help',
  },
];

export default data;
