const names = [
  { name: 'Alice', korean: '앨리스' },
  { name: 'Abel', korean: '아벨' },
  { name: 'Adia', korean: '애디아' },
  { name: 'Alexandra', korean: '알렉산드라' },
  { name: 'Amber', korean: '엠버' },
  { name: 'Alexandra', korean: '알렉산드라' },
  { name: 'Amber', korean: '엠버' },
  { name: 'Baby', korean: '베이비' },
  { name: 'Benny', korean: '베니' },
  { name: 'Brooke', korean: '브루크' },
  { name: 'Bety', korean: '베티' },
  { name: 'Bency', korean: '벤씨' },
  { name: 'Bety', korean: '베티' },
  { name: 'Bency', korean: '벤씨' },
  { name: 'Callie', korean: '캘리' },
  { name: 'Camille', korean: '카밀' },
  { name: 'Caitlin', korean: '캐이틀린' },
  { name: 'Caroline', korean: '캐롤린' },
  { name: 'Charlotte', korean: '샬롯' },
  { name: 'Caitlin', korean: '캐이틀린' },
  { name: 'Caroline', korean: '캐롤린' },
  { name: 'Charlotte', korean: '샬롯' },
  { name: 'Danielle', korean: '대니엘' },
  { name: 'Dua Lipa', korean: '두아 리파' },
  { name: 'Della', korean: '델라' },
  { name: 'Dora', korean: '도라' },
  { name: 'Dorothy', korean: '도로시' },
  { name: 'Dora', korean: '도라' },
  { name: 'Dorothy', korean: '도로시' },
];

export default names;
